# Generated by Django 4.1.1 on 2022-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
